version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres

  frontend:
    build: ./frontend2
    ports:
      - "4173:4173"
    depends_on:
      - backend

  postgres:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: IlLgtmzcRdnDsBAxdwNIJtcFghvJpbWn
      POSTGRES_DB: railway
